### PR TITLE
feat(frontend): change referral url structure

### PR DESCRIPTION
**Pull request by boriskubrik**
Changes the referral URL structure. Sticking to hash routing, as this is the only one that works with IPFS.

- `/r/0x1234` <- ref link for user with wallet 0x1234. `feeBps` is not set, using our default set at the backend.
- `/r/0x1234:20` <- ref link with user wallet 0x1234 and fee bps 20.
- Can append `/${fromToken}/${toToken}` after the referrer part.
- After processing the referrer, we remove it from the URL and redirect the user

### Testing
- [x] Added e2e tests
- [x] Works locally
- [x] Works on IPFS

https://github.com/sifiorg/sifi/assets/128667801/136d4aa5-7b19-4e03-8fdb-f13eb909918f

### CODE REVIEW

**Comment by boriskubrik** [comment]
IPFS does not work, they do recommend hash routing... ipfs://bafybeideemosl22f563f5k2qypq7zkxfpb2mj7xz33qqiumpo4ntfdx6hm/hosting/troubleshooting/#my-single-page-application-spa-breaks-when-changing-routes-via-an-ipfs-gatway

What do you think @immutablegoblin?

**Comment by xykota** [comment]
> ipfs://bafybeideemosl22f563f5k2qypq7zkxfpb2mj7xz33qqiumpo4ntfdx6hm/hosting/troubleshooting/#my-single-page-application-spa-breaks-when-changing-routes-via-an-ipfs-gatway

> IPFS gateways url are formatted in the following manner ipfs.io/ipfs/$hash. As such, the SPA might think that the root of the application is ipfs.io instead of ipfs.io/ipfs/$hash. For this reason, we recommend apps use hash routing to minimize such errors when using an IPFS gateway.

Is it enough to detect what the root directory of the site is, `/` or `/ipfs/$hash`? I have a strong preference for URL routing

**Comment by boriskubrik** [comment]
Tried routing via the base path in [3f3ff32](https://github.com/sifiorg/sifi/pull/479/commits/3f3ff328be5f14bccb1f8274d79da0ff4b32ab19), but it does not work on IPFS. Hashrouter seem to be the working solution.

For now, I think we can live with referral routing via the IFPS not working. We will display the sifi.org link in the UI anyway. 

Other routes should work, though. One compromise might be using `HashRouter` on IPFS and `BrowserRouter` on https. Looking for a working solution for this.

**Comment by xykota** [comment]
> Other routes should work, though. One compromise might be using `HashRouter` on IPFS and `BrowserRouter` on https. Looking for a working solution for this.

This is a really good idea!

**Comment by boriskubrik** [comment]
Reverted back to the hash router, as it seems this is our only option with IPFS.

**Comment by boriskubrik** [comment]
image

**Review by immutablegoblin — APPROVED** [review]
Looking good

**Pull request merged**
